project:
  type: website

website:
  title: "Data Science Portfolio"
  site-url: "https://oliverfanderson.com"
  favicon: "images/ofa_logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - contact.qmd
    logo: "/images/ofa_logo.png" # replace with the actual path to your logo file

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

