project:
  type: website

website:
  title: "Oliver F. Anderson, MS"
  description: "Computational biologist and data scientist specializing in bioinformatics, algorithm design, and AI automation for biotechnology and academic research."
  site-url: "https://oliverfanderson.com/"
  favicon: "images/ofa_logo.png"
  image: "images/ofa_logo.png"
  image-alt: "Oliver F. Anderson, MS - Computational Biologist and Data Scientist"
  twitter-card: true
  open-graph: true
  search: true
  back-to-top-navigation: true
  draft-mode: unlinked
  cookie-consent:
    type: implied
    style: simple
    palette: dark
  navbar:
    left:
      - icon: house-door-fill
        href: index.qmd
        text: Home
        aria-label: Home
      - icon: person-lines-fill
        href: about.qmd
        text: About
        aria-label: About
      - icon: file-bar-graph-fill
        href: projects.qmd
        text: Projects
        aria-label: Projects
      - icon: chat-square-fill
        href: contact.qmd
        text: Contact Me
        aria-label: Contact
      - icon: github
        href: "https://github.com/oliverfanderson"
        aria-label: GitHub
        target: "_blank"
      - icon: linkedin
        href: "https://linkedin.com/in/oliver-f-anderson"
        aria-label: LinkedIn
        target: "_blank"
      - icon: fingerprint
        href: "https://orcid.org/0009-0009-9985-4279"
        aria-label: ORCID
        target: "_blank"
    logo: "/images/ofa_logo.png"
    background: "#0454a4"
    pinned: true
    collapse: true
    toggle-position: right
  body-footer: "Oliver F. Anderson, MS -- Computational Biologist, Data Scientist, and Research Consultant based in Portland, Oregon. I design data-driven solutions in bioinformatics, machine learning, and AI automation for research and biotech."
  page-footer:
    center: 
      - text: "Website by Oliver F. Anderson | &copy; 2025"

author:
  name: "Oliver F. Anderson"
  orcid: 0009-0009-9985-4279
  affiliations:
    - name: "Reed College"
    - name: "Willamette University"
  email: "oliver.f.anderson.pro@gmail.com"
  url: "https://oliverfanderson.com/"
  image: "images/avatar.jpg"

format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
    code-fold: true
    code-summary: "Look at the code"
    include-in-header: _includes/schema.html

editor: visual

execute:
  freeze: auto

metadata:
  keywords: ["computational biology", "bioinformatics", "data science", "network analysis", "algorithms", "AI automation", "health informatics", "biotechnology research"]
  author: "Oliver F. Anderson, MS"
  description: "Computational biologist and data scientist specializing in graph algorithms, molecular networks, pathway analysis, and gene expression analysis."
  image: "images/avatar.jpg"
  lang: "en"
  robots: "index, follow"
  twitter-card: true
  open-graph: true