project:
  type: website

website:
  title: "Data Science Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

