project:
  type: website

website:
  title: "Oliver F. Anderson | Portfolio"
  description: "Portfolio of Oliver Anderson, MSDS — computational biologist and data scientist specializing in bioinformatics, protein networks, and AI automation for research and biotech."
  site-url: "https://oliverfanderson.com/"
  favicon: "images/ofa_logo.png"
  image: "images/ofa_logo.png"
  twitter-card: true
  open-graph: true
  cookie-consent:
    type: express
    style: interstitial
    palette: dark
  navbar:
    left:
      - icon: house-door-fill
        href: index.qmd
        text: Home
      - icon: person-lines-fill
        href: about.qmd
        text: About
        aria-label: About
      - icon: file-bar-graph-fill
        href: projects.qmd
        text: Projects
        aria-label: Projects
      - icon: chat-square-fill
        href: contact.qmd
        text: Contact Me
        aria-label: Contact
      - icon: github
        href: "https://github.com/oliverfanderson"
        aria-label: GitHub
      - icon: linkedin
        href: "https://linkedin.com/in/oliver-f-anderson"
        aria-label: LinkedIn
      - icon: fingerprint
        href: "https://orcid.org/0009-0009-9985-4279"
        aria-label: ORCID
    logo: "/images/ofa_logo.png"
    background: "#0454a4"
    pinned: true
    collapse: true
  page-footer:
    center: 
      - text: "Website by Oliver F. Anderson | &copy; 2025"

author:
  name: "Oliver F. Anderson"
  orcid: "https://orcid.org/0009-0009-9985-4279"
  affiliations:
    - name: "Reed College"
    - name: "Willamette University"
  email: "oliver.f.anderson.pro@gmail.com"
  url: "https://oliverfanderson.com/"
  image: "images/avatar.jpg"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Look at the code"
    include-in-header: _includes/schema.html

editor: visual

execute:
  freeze: auto

metadata:
  keywords: ["computational biology", "bioinformatics", "protein networks", "GO term enrichment", "AI automation", "data science consulting", "Portland OR"]
  author: "Oliver F. Anderson, MS"